### ISSUE TITLE
Cascading Worldgen 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [GlobbyPotato/Rockhounding_Surface#2]
[02:48:57] [Server thread/WARN] [FML]: Rockhounding: Surface loaded a new chunk (15, -19  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by GlobbyPotato** [comment]
Thanks for reporting. That seems to be caused by some wood invading a neighbour chunk while generating, hence ticking it. I did a fix that seems to no longer trigger it.
Please consider that the mod generates configurable elongated trunks, so in the case they are set to be very long by config, it may happen again on rare chances.

**Comment by P3rf3ctXZer0** [comment]
Rare is fine that was happening when moving slightly left and dropping frames to 45fp from 60 for about 120ticks

**Comment by P3rf3ctXZer0** [comment]
I figured it was a good idea to report in this case.

**Comment by GlobbyPotato** [comment]
Yeah, it was absolutely a nice catch, I overlooked this particular so the worldgen lag was possibly going to be a thing. Hopefully blocks stay inside the chunk they belong now.

**Comment by P3rf3ctXZer0** [comment]
Yeah its working now :)
