### ISSUE TITLE
Fossil Wood is not register like Wood... Caused problem with Better With Mods MIniBlocks

### ISSUE THREAD

**Issue by Fireztonez** [GlobbyPotato/Rockhounding_Surface#5]
Hello,
I have an issue with the the Mini-blocks (Sidings, molding and corner) made with any Fossil Plank. All the mini blocks is register in the Rock variant, while all other types of modpack wood are well detected as wood and save under the right variant. That cause a problem for the mining tool of the mini-blocks (Need an Pickaxe, not an Axe) and I can't leave it like that in my pack for sure!

I ask the dev of Better With Mods and and he has to look at his side and unfortunately there is nothing he can do to correct the problem and confirm that the problem came from your side and that it was very certain that you do not register properly with forge like wood...

The dev look into your git to found the problem, but the source-code is outdated, and can't find problem there... Can you please look for register correctly the wood like wood?!

Versions:
Rockhounding Surface: 3.07
Rockhounding Core: 3.07
Rockhounding Chemistry: 3.09
Rockhounding Ore Tier: 3.04
Minecraft: 1.12.2
Forge: 14.23.3.2675
Better With Mods: 2.1.12(-511)

Thank's
Fireztonez

**Comment by primetoxinz** [comment]
As the developer of BWM I can give some more context, as this isn't a bug per se. It is simply that my mini-blocks wrap the block material of the block which they take their texture from. In this case, I'm guessing that FossilPlanks are internally Material.ROCK and override the tool methods to allow the axe to break them, rather than a pickaxe. This causes my mini blocks to require a pickaxe, as there is no tile-entity aware version of getHarvestTool or other related methods. 
This is a feature request from Fireztonez part to make the planks Material.WOOD rather than ROCK, so they behave correctly from other perspectives.

**Comment by GlobbyPotato** [comment]
Hi, these blocks were supposed to don't fully behave like wood being them rocky fossils, so tried to turn off some wood specs like the isWood() methods and burning power and left a bit of a gate setting a ROCK material at some parts to see what would come up. Was not expecting the mod used that much to meet deeper features or mechanics.
If it suffices I will switch planks to WOOD material, the default tool should be already axe. In the config there is also an entry to turn on/off the oredicting "logWood", "plankWood"...
Sorry if it caused inconvenience.

**Comment by Fireztonez** [comment]
Ok, I did not think it was intentional, but yes, it will be fixed. For the oredict I did not see the config, I added to the oredict, but I will probably remove them if I can just configure it, issue to delete a line of script (Or simply no longer have them in oredict, I'm going to think about getting level) ... Yeah, you give exactly the same thought on these tree fossils as the developers of Better With Mods. But, the fact that to mine the planks they need an ax and not a pickaxe is my biggest concern for uniformity.

But, yes, adding it as Material.WOOD should be perfect to fix my worries. Question realism for example, to keep the contempt of rock fossil, I will see to ask for a better ax to cut these boards.

I wanted to say a big thank you for your suite of mods, which really add to that extra bit of realism I was looking for.

I can not wait to start working on the chemistry side of the mod, but I'm not there yet unfortunately in the development and testing of my modpack! I do not know yet how I will be able to integrate everything, in the best possible way because it is, everything seems rather complex and I'm not sure that everyone wants to go very far from it, but I'm sure of arrived at some great things with all that!

Thank's again!
Fireztonez

**Comment by GlobbyPotato** [comment]
Great, will upload it soon. If it works for the exploration/decoration task, uniforming to any wood will be not an issue.

Yeah, the chemistry mod is quite complicated indeed. It needs a specific scenario to make sense in a pack. The concept is that it works like an ore mod for late game recipes/processes, I just added the factory building puzzle to give depth and not just throw in the game random items. But with crafttweaker any machine can be used on it's own for convenience purposes.
While the mining path usually goes from mining-quarrying-multiplying-lens/void mining, the chemistry path wraps them all with new resources. In few words instead of using yet another copper ingot of the millions you may have in the storage to craft a late game stuff, you can use advanced material. It basically relies on how much you use it to balance effort and profit, othewise it will be critical for players. Hope it helps to decide if it fits for what you need.

**Comment by Fireztonez** [comment]
@GlobbyPotato yes exactly!

I will probably not use anything you add for sure, but somes things will be really nice... The only things, not sure not i think the machine from rockhounding chemestry doesn't take power? When void miner and any other late game things take lot of power... That's my only concern...

No worry for crafttweaker I already use a lot, and this is just the start... I add myself to lot of materials to the game, for realistic and advancement purposes by contenttweaker to... Just an example how far I go, I just change the alloy needed for tinker's casts... I use an alloy of magnesium, aluminum and zinc...

Thank's for your work and your explanation, that should be probably helpful for making my pack...

Fireztonez
